HW3 is completed
Ruslan-Androsenko/otus-home-work pull request #3
Opened 2023-08-20 19:33 UTC by Ruslan-Androsenko

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-08-21 06:26 UTC, vladislavmass requested changes
Хорошее начало. Радует что в коде есть комментарии. У этого кода слишком высокая алгоритмическая сложность. Подсчет количество слов имеет сложность O(N)*O(M), сортировка делается за несколько проходов по массивам при том, что может делаться за 1. Все это раздувает код и делает его менее читаемым.

Предлагаю заменить код в строка 37-49 на простой подсчет числа элементов в `map[string]int`

2023-08-27 04:48 UTC, vladislavmass approved these changes
Отличная работа. Сложность упала, тесты новые написаны. Работа принята. 9/10. -1за читаемость кода из за метода ` sortMapByFrequency` так как его название не отображает его назначение

2023-08-27 04:48 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +func sortMapByFrequency(frequencies map[string]int) []FrequencyAnalysis {
Какой вывод мы можем сделать из названия? что этот метод сортирует мапу и на выходе мы ожидаем отсортированную мапу( звучит конечно как бред) что бы я предложил сделать. 
1) либо вынести код в строках 63-71 в метод `getHighFrequencyWords`, либо этот код вынести в отдельный метода и просто его вызывать  в `getHighFrequencyWords`. 
2)либо переименовать этот метода, либо вообще вынести сортировку в метод  `getHighFrequencyWords` так как метод состоящий всего из 1 вызова это очень спорный вопрос

2023-08-27 07:31 UTC, Ruslan-Androsenko commented on hw03_frequency_analysis/top.go
> +func sortMapByFrequency(frequencies map[string]int) []FrequencyAnalysis {
Я кстати изначально так и делал, но мне это не понравилось и я решил вынести этот кусок в отдельную функцию))

2023-08-27 10:31 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +func sortMapByFrequency(frequencies map[string]int) []FrequencyAnalysis {
Формально было бы логичнее, если это прям надо, выделить в одну функция парсинг текста в слайс слов. 2 функция считает количество через мапу и потом пишет в слайс. Возвращаю слай, а 3 уже сортирует. Тогда да, у каждой функции своя зона ответственности и все ок.

2023-10-25 19:42 UTC, merged